# Generated by Django 5.2.7 on 2025-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
