# Generated by Django 5.2.7 on 2025-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
