# Generated by Django 5.2.7 on 2025-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appuser_groups_appuser_is_active_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
