# Generated by Django 5.2.7 on 2025-10-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_appuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
