# Generated by Django 5.2.7 on 2025-10-18 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_appuser_last_logout_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_logout_at',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='token',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_class',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=255, null=True)),
                ('user_class', models.CharField(blank=True, db_column='class', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_state',
                'ordering': ['-last_login'],
            },
        ),
    ]
