# Generated by Django 5.2.7 on 2025-10-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_country_appuser_avatar_userinfo_city_userinfo_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_infos', to='base.country'),
        ),
    ]
