# Generated by Django 5.2.7 on 2025-10-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_language_alter_appuser_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['board', 'name']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_class',
        ),
    ]
