# Generated by Django 5.2.7 on 2025-10-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_subject_options_remove_subject_subject_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='sort_order',
        ),
    ]
