# Generated by Django 5.2.7 on 2025-10-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_unit_options_remove_unit_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
    ]
