# Generated by Django 5.2.7 on 2025-10-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_lesson_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sort_order',
        ),
    ]
