# Generated by Django 5.2.7 on 2025-10-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_lesson_options_remove_lesson_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='stem',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='asset',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('ssl', 'Single Selection'), ('mcq', 'Multiple Choice'), ('true_false', 'True/False')], default='mcq', max_length=50),
        ),
    ]
