# Generated by Django 5.2.7 on 2025-10-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_question_options_rename_stem_question_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.question')),
            ],
            options={
                'db_table': 'answer',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['question'], name='idx_answer_question')],
            },
        ),
    ]
