# Generated by Django 5.2.7 on 2025-10-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='base.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='base.lesson'),
            preserve_default=False,
        ),
    ]
