# Generated by Django 5.2.7 on 2025-10-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_city_alter_userinfo_city_state_city_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='base.unit')),
            ],
            options={
                'db_table': 'unit_parts',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['unit'], name='idx_unitpart_unit')],
            },
        ),
    ]
