# Generated by Django 5.2.7 on 2025-10-25 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_unitpart'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='idx_question_lesson',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.unit'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['unit'], name='idx_question_unit'),
        ),
    ]
