# Generated by Django 5.2.7 on 2025-10-25 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_question_idx_question_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='base.unit')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='base.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkpoint',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earned', models.FloatField(default=0)),
                ('out_of', models.FloatField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='base.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score',
                'ordering': ['unit'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badge',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['user'], name='idx_checkpoint_user'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['subject'], name='idx_checkpoint_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('user', 'subject')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user'], name='idx_score_user'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['unit'], name='idx_score_unit'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
