# Generated by Django 5.2.7 on 2025-10-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_checkpoint_score_userbadge_delete_progress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkpoint',
        ),
    ]
