# Generated by Django 5.2.7 on 2025-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='xp',
            field=models.FloatField(default=0),
        ),
    ]
