# Generated by Django 5.2.7 on 2025-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_userinfo_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpart',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_class',
            field=models.CharField(blank=True, db_column='user_class', max_length=50, null=True),
        ),
    ]
